version: '3.9'

services:
  frontend:
    build:
      context: ./exFrontEnd
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./exBackEnd
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
