apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: Dummy-Value # FOR TESTING ONLY, DO NOT PUSH TO REPO!!!
  AWS_SECRET_ACCESS_KEY: Dummy-Value # FOR TESTING ONLY, DO NOT PUSH TO REPO!!!
  AWS_REGION: eu-central-1
